### ISSUE TITLE
lxqt-runner doesn't get input automatically

### ISSUE THREAD

**Issue by stefonarch** [YaLTeR/niri#641] opened 2024-08-30 10:47 UTC
Launching lxqt-runner with `Alt+Space { spawn "lxqt-runner"; }`  it doesn't take keyboard focus. 
Other compositors are fine now (except sway release) with it now. 
Code is here, layer is overlay:
https://github.com/lxqt/lxqt-runner/blob/7900d00918145e90c5fea0e3b9b059b155bd3cec/dialog.cpp#L210

Tested a moment with `KeyboardInteractivityExclusive`, still the same.

I wasn't able to build niri-git from AUR (left a comment there), so if this is fixed in git please ignore.

Context: we've integrated 6 compositors in the upcoming [wayland-session](https://github.com/lxqt/lxqt-wayland-session/) and I noticed  that the other LXQt components like desktop, panel and notifications are working fine in niri. Tecnically we have panel backends for kwin_wayland, wlroots and x11 and it's possible to add dedicated backends for compositors.

### System Information

* niri version: 
Niri 0.1.8

* Distro:  Arch

* GPU: 
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    vendor: ASUSTeK driver: amdgpu v: kernel arch: GCN-5 bus-ID: 02:00.0

**Comment by YaLTeR** [comment] 2024-08-30 11:50
I don't think on-demand surfaces get keyboard focus automatically. Should they? Things like bars also use on-demand, and they shouldn't get keyboard focus at startup.

Exclusive surfaces though should get keyboard focus automatically, not sure why that wouldn't work.

**Comment by stefonarch** [comment] 2024-08-30 12:24
FYI the discussion in labwc: https://github.com/labwc/labwc/issues/1653

I'll recheck with `:KeyboardInteractivityExclusive` again - the dropdown QTerminal (overlay too) has the same issue in Niri.

**Comment by stefonarch** [comment] 2024-08-30 13:53
Rechecked for good - `KeyboardInteractivityExclusive` is working indeed, but the point is that we can't use this as the runner won't close on loosing focus when nothing is launched  and would have to be dismissed manually by Esc always.

**Comment by YaLTeR** [comment] 2024-08-30 14:11
What is the expected behavior then? Does a surface get focus if it spawns with on-demand? What about if a surface gets on-demand afterwards?

Maybe it could be worked around on the client side by spawning with exclusive, then switching to on-demand next surface commit?

**Comment by stefonarch** [comment] 2024-08-30 15:08
>Maybe it could be worked around on the client side by spawning with exclusive, then switching to on-demand next surface commit?

I think this won't work if called by accident by shortcut and it should disappear on every other action. Runner works basically fine on every other compositor now  (afaik also sway git as someone reported, although I can't test it).

River had the same issue and followed labwc: https://codeberg.org/river/river/issues/1111#issuecomment-2096056

**Comment by YaLTeR** [comment] 2024-09-02 14:53
Copying the relevant bit here:

> Change river's current behavior to give focus to on_demand layer surfaces on map if there is no exclusive layer surface on the top or overlay layer present. The only argument against this UX that I see is that it doesn't really make sense to focus a status bar on map. I suspect that this is a non-issue in practice though as status bars are generally only mapped once at the start of the session.

**Comment by stefonarch** [comment] 2024-09-09 14:20
https://github.com/lxqt/lxqt-menu-data/ is installed?

**Comment by YaLTeR** [comment] 2024-09-09 14:43
Yeah:
```
└─ pacman -Q lxqt-menu-data
lxqt-menu-data 2.0.0-1
```
I installed the entire lxqt group.

**Comment by FreeFull** [comment] 2024-09-09 17:14
I had to right-click on the menu button, and select a menu file in the config. I'm on Arch, so the menu file was in `/etc/xdg/menus/lxqt-applications.menu`, not sure where it'd be on Nix

**Comment by YaLTeR** [comment] 2024-09-09 17:21
I confirm that helps with the panel menu but not with the runner.

**Comment by stefonarch** [comment] 2024-09-09 18:20
Could be you didn't set the needed env vars (set if `startlxqt` is used):
`XDG_MENU_PREFIX=lxqt-` ?

**Comment by YaLTeR** [comment] 2024-09-09 19:02
That made the menu show up on the panel and removed the menu message in lxqt-runner, but lxqt-runner still doesn't show up. Looking at the WAYLAND_DEBUG=1 log, it doesn't even attempt to show any surface?

**Comment by stefonarch** [comment] 2024-09-09 19:48
No idea about your setup. Probably the easiest way would be to compile (no AUR package yet) https://github.com/lxqt/lxqt-wayland-session/ and start `startlxqtwayland` or use a DM for it, in "Session Settings" the compositor to use can be set.

It works fine on at least 7 different compositors, launched by command or by shortcut:

`    Alt+Space { spawn "lxqt-runner"; }`

**Comment by FreeFull** [comment] 2024-09-09 19:54
> That made the menu show up on the panel and removed the menu message in lxqt-runner, but lxqt-runner still doesn't show up. Looking at the WAYLAND_DEBUG=1 log, it doesn't even attempt to show any surface?

It seems that the first time you run lxqt-runner it stays around as a daemon and doesn't show anything, and then if you run it again it'll actually show up

**Comment by YaLTeR** [comment] 2024-09-09 19:58
Huh, indeed. Thanks.

**Comment by stefonarch** [comment] 2024-09-09 20:39
>It seems that the first time you run lxqt-runner it stays around as a daemon and doesn't show anything, and then if you run it again it'll actually show up

Indeed it's module is started usually by `lxqt-session` - otherwise you need to issue the command twice. Could have thought of that sorry, glad you solved.

**Comment by YaLTeR** [comment] 2024-09-10 07:27
Okay, 7d5785e96f3deaee1bb279ee16b3b12f05344951 should now give focus to newly mapped on-demand surfaces. Please give it a try.

Though, one UX problem with this is that if you have focus-follows-mouse, then you can't really move the mouse towards lxqt-runner, since it will likely cross another window, which will switch the focus back from lxqt-runner, and close it. This is only a problem when lxqt-runner gets focus upon opening.

**Closed by YaLTeR** 2024-09-10 07:27 UTC
Labels: bug
