### ISSUE TITLE
Cursor is corrupted after waking from sleep

### ISSUE THREAD

**Issue by raiguard** [YaLTeR/niri#634] opened 2024-08-28 19:14 UTC
When I wake my PC from sleep, the cursor is corrupted. It remains this way until the cursor image is changed.

Taking a screenshot was impossible, so here is a photo:

![image](https://github.com/user-attachments/assets/30a6a2a4-cc61-491a-a8af-0f259242118e)

### System Information

* niri version: niri 0.1.8 (0.0.git.1307.598b27f8)
* Distro: Fedora 40 Workstation
* GPU: AMD RX 6800xt
* CPU: Intel i9-10900k

**Comment by YaLTeR** [comment] 2024-08-28 19:31
This is most likely a driver bug, nothing niri can help.

**Comment by raiguard** [comment] 2024-08-30 21:53
It only occurs on my desktop and only with Niri, but I agree that the root cause is likely in the drivers. I will poke around more and will let you know if I find anything.

**Comment by g3r** [comment] 2024-08-31 15:00
I don't think it is a driver bug, I have the same cursor corruption on Nvidia GPU (proprietary driver). Also I can't reproduce on other compositors

Manjaro
Nvidia 960
Intel i7-6700k

**Comment by YaLTeR** [comment] 2024-08-31 15:01
Does it work fine on cosmic too?

**Comment by YaLTeR** [comment] 2024-11-04 06:27
Any updates on this? I've seen some cases of this corrupted cursor myself, sometimes when connecting an external output to a sleeping (powersaving) dGPU in a laptop. But I'm not sure it's something on niri side.

**Comment by g3r** [comment] 2024-11-04 10:57
Still happens to me. I didn't see it happening in Cosmic but is hard to reproduce during normal use.
I don't use sleep

Steps to reproduce reliably in niri: 
Enable ```warp-mouse-to-focus```
Shutdown computer ( logout or reboot is not enough)
After start up don't move the mouse and open firefox with a shortcut
The cursor moves to the window and appears corrupted
Moving the cursor until it changes shape fixes it

**Comment by g3r** [comment] 2024-11-04 14:50
Update: I saw the glitch in Cosmic too, maybe it's something in smithay

**Comment by YaLTeR** [comment] 2024-11-04 14:51
Well yeah it's probably not a niri issue so I'll close it (feel free to reopen if it does turn out to be a niri issue). I still suspect it's something in the driver.

**Closed by YaLTeR** 2024-11-04 14:51 UTC
Labels: bug, question
