### ISSUE TITLE
Wrong positioning and sizing of some layer shell applications (bemenu, tofi)

### ISSUE THREAD

**Issue by itshog** [YaLTeR/niri#575] opened 2024-08-08 09:18 UTC
### System Information

* niri version: niri 0.1.7 (unknown commit) (the bug appears both in the version from Arch repo and when building from source with `cargo build --release`)

* Distro: Arch Linux

* GPU: Intel Corporation UHD Graphics 620

* CPU: Intel(R) Core(TM) i5-8350U

### Description
Some menu programs using layer-shell, like [bemenu](https://github.com/Cloudef/bemenu) and [tofi](https://github.com/philj56/tofi), are wrongly positioned on the screen: in particular, bemenu's `--center` flag and tofi's `anchor = center` option seem to be completely ignored (it should be noted that, in the case of tofi, _manual_ positioning with `margin-*` appears to be working as expected). When it comes to the sizing, bemenu's `-W` flag is ignored, while tofi respects the size specified in the config file but it stretches its content in strange ways (see pictures). Both programs work fine when using one of the major wlroots compositors (I included screenshots taken in [river](https://codeberg.org/river/river) for reference).

I apologize beforehand in case it turns out that the issue isn't on niri's end, as it may be a bug in those two programs or in the underlying smithay library (or maybe those programs weren't meant to be run outside of wlroots to begin with).

Similar issue that may be useful (?): [bemenu issue](https://github.com/Cloudef/bemenu/issues/223)

### Pictures
- bemenu, river
![bemenu-river](https://github.com/user-attachments/assets/90faee58-6d25-4653-a1e2-ccbaf574e0a0)

- tofi, river
![tofi-river](https://github.com/user-attachments/assets/d98916d1-2c89-4a2b-864c-1b7b94cf706b)

- bemenu, niri
![bemenu-niri](https://github.com/user-attachments/assets/39e6ee26-cd50-4004-a85c-96f6abf6711f)

- tofi, niri
![tofi-niri](https://github.com/user-attachments/assets/acd6f954-86cb-45f9-9644-8355217c3a40)

### Logs
All logs are collected by adding `WAYLAND_DEBUG=1` before the command (let me know if there are other useful logs I should collect)

- [bemenu, river](https://0x0.st/XVgE.log)
- [tofi, river](https://0x0.st/XVg6.log)
- [bemenu, niri](https://0x0.st/XVgU.log)
- [tofi, niri](https://0x0.st/XVgG.log)

Anyway, thanks for the great project! The "scrolling" paradigm is quite different from the classic tiling that I'm used to, but it sure has a lot of potential!

**Comment by YaLTeR** [comment] 2024-08-08 16:39
Hey, so I suspect this might be these clients relying on wlroots-specific quirks of implementing underspecified anchoring combinations. You could try on KWin which is another separate layer-shell impl to see if the bugs reproduce there.

We already had an issue like this before with fuzzel, turned out KWin had the same behavior as Smithay, so it got fixed in fuzzel.

**Comment by itshog** [comment] 2024-08-08 18:56
> Hey, so I suspect this might be these clients relying on wlroots-specific quirks of implementing underspecified anchoring combinations. You could try on KWin which is another separate layer-shell impl to see if the bugs reproduce there.

I just tried both bemenu and tofi in plasma 6, and the centering options still seem to be ignored by the compositor. The sizing on the other hand works as expected, as is the case under wlroots.

**Comment by YaLTeR** [comment] 2024-08-08 19:01
I see, thanks for testing. Well, layer-shell sizing and positioning is fully implemented in Smithay. I expect you'll see the same behavior as in niri in cosmic-comp or [anvil](https://github.com/Smithay/smithay/tree/master/anvil). That is to say, parts of this issue which are decidedly not client problems are probably better moved to the Smithay repository.

**Comment by itshog** [comment] 2024-08-08 19:21
> I expect you'll see the same behavior as in niri in cosmic-comp or [anvil](https://github.com/Smithay/smithay/tree/master/anvil).

How can I test in anvil/smallvil? I managed to compile and run them, but I can't figure out how to start applications

**Comment by YaLTeR** [comment] 2024-08-08 19:32
In anvil there's a [hardcoded Super+Enter shortcut](https://github.com/Smithay/smithay/blob/c542d097b9b62ae5dbf34afc639692d4e7213b88/anvil/src/input_handler.rs#L1336) to spawn weston-terminal (you can hardcode this to something else). Alternatively, from a terminal elsewhere: `env WAYLAND_DISPLAY=wayland-2 some-command`.

**Comment by itshog** [comment] 2024-08-08 19:39
> In anvil there's a [hardcoded Super+Enter shortcut](https://github.com/Smithay/smithay/blob/c542d097b9b62ae5dbf34afc639692d4e7213b88/anvil/src/input_handler.rs#L1336) to spawn weston-terminal

Sorry, I was using a virtual machine and Super+Enter kept getting "eaten" by my host compositor. Anyway, anvil seems to behave just like niri, with both bemenu and tofi being unable to properly position and size themselves.

**Comment by YaLTeR** [comment] 2024-11-08 14:45
Well I guess this is either a client issue or should be opened on Smithay since it reproduces on Anvil. If there's anything niri-specific, feel free to reopen.

**Closed by YaLTeR** 2024-11-08 14:45 UTC
Labels: bug
