### ISSUE TITLE
Focused overlays don't work.

### ISSUE THREAD

**Issue by KaitlynEthylia** [YaLTeR/niri#433] opened 2024-06-10 21:29 UTC
So I've tried using both Eww and Rofi on niri, and experienced the same bug with bog of them; (this only happens on eww when the window is set to focusable)

after the window is open, the keyboard becomes unresponsive. I can't close the programme, I can't focus another window, I want open another window. the only thing I'm able to do is Mod+Shift+E to close niri entirely 

### System Information

* niri version: 0.1.6

* Distro: NixOS 24.05

* GPU: Nvidia GTX 1050 ti

* CPU: Intel i3 2300

**Comment by YaLTeR** [comment] 2024-06-11 03:37
This is something others have been reporting, but I could never reproduce myself. What's your input -> keyboard -> xkb niri config?

**Comment by YaLTeR** [comment] 2024-07-17 04:16
With rofi it seems to be a rofi issue that was fixed in an unreleased version? https://github.com/davatorium/rofi/discussions/2008

**Comment by jjramsey** [comment] 2024-09-07 20:35
> This is something others have been reporting, but I could never reproduce myself. What's your input -> keyboard -> xkb niri config?

Are you trying it out with X11-based rofi or the rofi-wayland fork at https://github.com/lbonn/rofi?

**Comment by YaLTeR** [comment] 2024-11-04 06:31
So this issue is likely due to ewww requesting exclusive keyboard focus when it is focusable. Then niri gives it keyboard focus as requested.

You can set ewww as not focusable, or I think there should be some setting to make it take on-demand keyboard focus, rather than exclusive, which will also work fine.

**Comment by YaLTeR** [comment] 2024-11-13 11:36
Closing because I'm fairly sure everything is working as intended.

**Closed by YaLTeR** 2024-11-13 11:36 UTC
Labels: bug
