### ISSUE TITLE
VRR property isn't reset

### ISSUE THREAD

**Issue by andreasKroepelin** [YaLTeR/niri#114] opened 2024-01-20 21:40 UTC
I am using the current 0.1.0-beta version from the COPR package. After trying it out for some minutes, an issue starts to appear randomly: The windows stop being rendered (i.e. typed characters don't appear or a scrolled page doesn't move) until the mouse is moved. Let me know if you need more details!

I love the ideas of niri btw, I'm looking forward to its further development :)

**Comment by YaLTeR** [comment] 2024-01-21 03:16
Hey! That sounds weird, what hardware are you on? Specifically GPU and graphics drivers. I know an issue similar to this exists on Nvidia with the proprietary driver, and I'm not quite sure what causes it.

**Comment by andreasKroepelin** [comment] 2024-01-21 16:42
`neofetch` says `Intel TigerLake-LP GT2 [Iris Xe Graphics]`. Does that help?

**Comment by YaLTeR** [comment] 2024-01-21 16:49
Is it some specific app that you're seeing the issue appear on? What about other apps, or niri itself, e.g. does switching workspaces work fine?

**Comment by andreasKroepelin** [comment] 2024-01-21 17:44
I noticed it in alacritty and Firefox but haven't tested other apps. Switching workspaces seems to be fine.

**Comment by YaLTeR** [comment] 2024-01-21 17:54
Is there anything suspicious in `journalctl --no-hostname -eb /usr/bin/niri` perhaps? Also if you run something like `weston-simple-egl` on the side which constantly redraws the monitor, then do things work fine?

**Comment by YaLTeR** [comment] 2024-02-03 05:56
Hey, does this still happen? Also does it happen with constant monitor redrawing as I suggested? There's not much I can do about this issue in its current state unfortunately; also it's likely a Smithay or a driver issue.

**Comment by andreasKroepelin** [comment] 2024-02-03 18:38
Let me install the 0.1.0 version and try again!

**Comment by andreasKroepelin** [comment] 2024-02-03 18:40
> Is there anything suspicious in `journalctl --no-hostname -eb /usr/bin/niri` perhaps? Also if you run something like `weston-simple-egl` on the side which constantly redraws the monitor, then do things work fine?

As to that, there was nothing suspicious in `journalctl` and running `weston-simple-wgl` didn't help. Sorry, I forgot to answer!

**Comment by YaLTeR** [comment] 2024-02-04 05:01
> running `weston-simple-egl` didn't help

Huh, then it sounds like something is wrong with the damage. Perhaps a driver bug?

I should look how hard it is to add a debug flag that disables damage.

**Comment by YaLTeR** [comment] 2024-02-04 05:02
> The windows stop being rendered (i.e. typed characters don't appear or a scrolled page doesn't move) until the mouse is moved.

Does this mean until the mouse moves *at all* or until the mouse moves over the part of the window that was supposed to be redrawn?

**Comment by Supreeeme** [comment] 2024-02-06 05:10
https://gitlab.com/gabmus/envision

**Comment by Supreeeme** [comment] 2024-02-06 05:17
I can reproduce this, but my symptoms are a little different. Firefox will seemingly stop rendering for about a second or so, and then it'll start back up. If I constantly move the mouse while typing or run `weston-simple-egl` while typing the problem doesn't happen. Nothing of interest in journalctl. I'm on AMD (RX 6600).

**Comment by YaLTeR** [comment] 2024-02-06 05:38
That's really odd, haven't seen that myself.

**Comment by muemo** [comment] 2024-02-06 21:38
I can reproduce it as well. The window does not render for several seconds if I don't move the mouse. This affects several applications, e.g. firefox, alacritty. `weston-simple-egl` prevents it. There are no suspicious logs.
I have an intel card, Iris Plus Graphics G7

**Comment by Supreeeme** [comment] 2024-02-06 23:16
Interesting notes:
- It does not occur on either of my laptops - one Thinkpad on Ubuntu with Intel Xe graphics, one Macbook on Arch with Intel Iris Graphics 530, but does occur on my desktop (with a RX 6600)
- It does not occur when running on Wayland, i.e. niri on niri won't show the issue, but niri launched from a TTY will on my desktop.

I'd like to help debug/fix this, but I'm not sure where to even start...

**Comment by Supreeeme** [comment] 2024-02-07 00:23
Oh, I figured this out. For me at least, this is caused by VRR/adaptive sync being enabled in sway. If I run sway and enable adaptive sync (`outputs * adaptive_sync on`) I'll see the stuttering in niri, even if I close sway first. If I then either turn off adaptive sync from sway or run cage/cagebreak from a tty and then close it, the stuttering in niri goes away. This seems to be a niri issue because it doesn't happen on cagebreak, and can be fixed by simply switching to a tty with cagebreak.

**Comment by YaLTeR** [comment] 2024-02-07 04:26
Wow, thanks, that is very helpful! I can reproduce this on my setup; actually for whatever reason enabling adaptive sync on my main monitor causes it to literally modeset every redraw, which persists across a TTY switch to niri. This is something we can fix though.

**Comment by andreasKroepelin** [comment] 2024-03-14 19:48
I can happily report that this problem does not happen for me anymore with the current release, so I am daily-driving niri now :)

**Comment by YaLTeR** [comment] 2024-03-15 03:15
Awesome, looks like your problem was also fixed by the frame callback fixes in 0.1.3. I'll leave this open though because VRR needs some specific support in the compositor and if it's enabled while the compositor doesn't know, that's not very good.

**Comment by YaLTeR** [comment] 2024-04-14 05:46
VRR property should now be supported and reset as necessary in 3c6d8062c5c9b31afb5eeacd66a58b19b6566d9f.

**Closed by YaLTeR** 2024-04-14 05:46 UTC
Labels: bug
