### ISSUE TITLE
Switching window on click left or right egde of the screen

### ISSUE THREAD

**Issue by nebulosa2007** [YaLTeR/niri#265] opened 2024-03-25 09:22 UTC
### System Information

* niri version: niri 0.1.3 (v0.1.3-73-ge5bd111)

* GPU: Intel 2nd Generation Core Family Integrated

* CPU: Intel i3-2310M

I try to clarify new niri settings - opacity for windows etc... So, I make the config as default as possible and noticed that switching on click for edges of the screen stopped working when I set `focus-fing` is on and `border` is off. Somehow it switches only from `foot` terminal window (to left or right) but not works for `firefox`, `telegram`, `alacritty`, `nautilus` etc either, when their windows is maximized.

Adding `prefer-no-csd` doesn't do nothing.

What I missed?

[My current config](https://0x0.st/XsbS.txt)

**Comment by YaLTeR** [comment] 2024-03-25 10:10
Hey, I think you need to add left and right struts.

**Comment by nebulosa2007** [comment] 2024-03-25 10:26
Tested with
```console
    struts {
        left 1
        right 1
        // top 64
        // bottom 64
    }
```
Not works. With more width like `5` or more its like usual switching, but it scroll to click in `firefox` or `telegram`. 

The main question is why it works as it should for `foot` only, not depending on the `struts` setting.

**Comment by YaLTeR** [comment] 2024-03-25 14:05
I'm not entirely sure, but I suspect it is due to the input region extending slightly outside the geometry for these windows to support mouse edge resizing. `foot` with CSD seems to have quite a small region for this in comparison to others.

**Comment by nebulosa2007** [comment] 2024-03-26 10:28
As a result of editing the config, I found out that if you want to manage the opacity of the windows, you can do it in two variants:

Note: the focus ring is off and border is on in both variants (they seem to me to have similar functionality, but edge clicking only works for borders)

1. If you want to manage all windows opacity add the rule like:
```console
window-rule {
    draw-border-with-background false  // or set `prefer-no-csd` abobe
    match is-active=false
    opacity 0.8
}
``` 
2. Only for apps that can manage opacity on their own:
```console
window-rule {
    match app-id="foot"
    draw-border-with-background false
}
```

**Comment by YaLTeR** [comment] 2024-03-27 03:40
Closing because it's not a bug.

**Closed by YaLTeR** 2024-03-27 03:40 UTC
Labels: bug

**Comment by YaLTeR** [comment] 2024-04-02 17:14
I guess the windows you use have 10 px wide resize regions.
